Vagrant.configure("2") do |config|

  # For more information on the modifyvm commands see http://www.virtualbox.org/manual/ch08.html
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false

  config.vm.synced_folder "docker", "/data/docker"
  config.vm.synced_folder "scripts", "/data/scripts"

  config.vm.define "srv-docker" do |srv|
    srv.vm.hostname = "srv-docker"
    srv.vm.network    "private_network", ip: "10.10.10.1"
    srv.vm.provider   "virtualbox" do |vb|
      vb.name   = "srv-docker"
      vb.memory = 512
    end
    srv.vm.provision "docker" do |d|
        d.images = ["ubuntu:14.04"]
    end
  end

end
